server:
  port: 8081
  
spring:
  profiles.active: local
  
  # 데이터 소스 설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/testDb?charSet=UTF-8
    #driver-class-name: org.postgresql.Driver 
    #url: jdbc:postgresql://localhost:5432/testDb?charSet=UTF-8
    username: ins
    password: usr!23
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  # JPA 설정
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          "[import_files_sql_extractor]": org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        "[current_session_context_class]": org.springframework.orm.hibernate5.SpringSessionContext
        "[default_batch_fetch_size]": ${chunkSize:100}
        "[jdbc.batch_size]": 20
        "[order_inserts]": true
        "[order_updates]": true
        "[format_sql]": true
        #temp:
          #use_jdbc_metadata_defaults: false
          
# cors 설정
cors:
  allowed-origins: 'http://localhost:8082'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600